using System.Xml;

namespace AzureApimPolicyGen;

internal sealed class PolicyXmlWriter : IDisposable
{
    private XmlWriter _xmlWriter;
    public bool _baseCalled;

    private static XmlWriterSettings XmlOptions = new XmlWriterSettings
    {
        Indent = true,
        OmitXmlDeclaration = true,
        ConformanceLevel = ConformanceLevel.Document,
    };

    public PolicyXmlWriter(Stream stream)
    {
        _xmlWriter = XmlWriter.Create(stream, XmlOptions);
        _xmlWriter.WriteComment($" Generated by AzureApimPolicyGen v1. ({DateTime.Now}) ");
        _xmlWriter.WriteStartElement("policies");
    }

    public void Base()
    {
        if (_baseCalled) return;

        _xmlWriter.WriteStartElement("base");
        _xmlWriter.WriteEndElement();
        _baseCalled = true;
    }

    public void Inbound()
    {
        StartPhase("inbound");
    }

    public void Backend()
    {
        StartPhase("backend");
    }


    public void Outbound()
    {
        StartPhase("outbound");
    }

    public void OnError()
    {
        StartPhase("on-error");
    }

    public void EndElement()
    {
        if (!_baseCalled)
            _xmlWriter.WriteComment($" WARNING: Base was not called. Upstream policies will NOT be executed. ");

        _xmlWriter.WriteEndElement();
    }

    public void Close()
    {
        _xmlWriter.WriteFullEndElement();
        _xmlWriter.Flush();
        _xmlWriter.Close();
    }

    public void Dispose()
        => _xmlWriter.Dispose();

    private void StartPhase(string name)
    {
        _baseCalled = false;
        _xmlWriter.WriteStartElement(name);
    }

    private static string? BoolValue(bool? value)
    {
        if (value.HasValue)
            return value.Value ? "true" : "false";
        return null;
    }

    // Authentication

    public void AuthenticationBasic(string username, string password)
    {
        _xmlWriter.WriteStartElement("authentication-basic");
        _xmlWriter.WriteAttributeString("username", username);
        _xmlWriter.WriteAttributeString("password", password);
        _xmlWriter.WriteEndElement();
    }

    public void AuthenticationCertificate(string? thumbprint, string? certificate, string? body, string? password)
    {
        _xmlWriter.WriteStartElement("authentication-certificate");
        _xmlWriter.WriteAttributeStringOpt("thumbprint", thumbprint);
        _xmlWriter.WriteAttributeStringOpt("certificate", certificate);
        _xmlWriter.WriteAttributeStringOpt("body", body);
        _xmlWriter.WriteAttributeStringOpt("password", password);
        _xmlWriter.WriteEndElement();
    }

    public void AuthenticationManagedIdentity(string resource, string? clientId, string? outputTokenVariableName, bool ignoreError)
    {
        _xmlWriter.WriteStartElement("authentication-managed-identity");
        _xmlWriter.WriteAttributeString("resource", resource);
        _xmlWriter.WriteAttributeStringOpt("client-id", clientId);
        _xmlWriter.WriteAttributeStringOpt("output-token-variable-name", outputTokenVariableName);
        _xmlWriter.WriteAttributeString("ignore-error", BoolValue(ignoreError));
        _xmlWriter.WriteEndElement();
    }

    // Cache

    public void CacheLookup(string varyByDeveloper, string varyByDeveloperGroups, string? allowPrivateResponseCaching,
        string? cacheType, string? downstreamCacheType, string? mustRevalidate, Action? varyBy)
    {
        _xmlWriter.WriteStartElement("cache-lookup");
        _xmlWriter.WriteAttributeString("vary-by-developer", varyByDeveloper);
        _xmlWriter.WriteAttributeString("vary-by-developer-groups", varyByDeveloperGroups);
        _xmlWriter.WriteAttributeStringOpt("allow-private-response-caching", allowPrivateResponseCaching);
        _xmlWriter.WriteAttributeStringOpt("caching-type", cacheType);
        _xmlWriter.WriteAttributeStringOpt("downstream-caching-type", downstreamCacheType);
        _xmlWriter.WriteAttributeStringOpt("must-revalidate", mustRevalidate);
        if (varyBy is not null) varyBy();
        _xmlWriter.WriteEndElement();
    }
    public void CacheLookup_VaryByHeader(string name)
        => _xmlWriter.WriteElementString("vary-by-header", name);
    public void CacheLookup_VaryByParam(string nameOrNames)
        => _xmlWriter.WriteElementString("vary-by-query-parameter", nameOrNames);

    public void CacheLookupValue(string variableName, string key, string? defaultValue, string? cacheType)
    {
        _xmlWriter.WriteStartElement("cache-lookup-value");
        _xmlWriter.WriteAttributeString("variable-name", variableName);
        _xmlWriter.WriteAttributeString("key", key);
        _xmlWriter.WriteAttributeStringOpt("default-value", defaultValue);
        _xmlWriter.WriteAttributeStringOpt("caching-type", cacheType);
        _xmlWriter.WriteEndElement();
    }

    public void CacheStore(string duration, string? cacheResponse)
    {
        _xmlWriter.WriteStartElement("cache-store");
        _xmlWriter.WriteAttributeString("duration", duration);
        _xmlWriter.WriteAttributeStringOpt("cache-response", cacheResponse);
        _xmlWriter.WriteEndElement();
    }

    public void CacheStoreValue(string duration, string key, string value, string? cacheType)
    {
        _xmlWriter.WriteStartElement("cache-store-value");
        _xmlWriter.WriteAttributeString("duration", duration);
        _xmlWriter.WriteAttributeString("key", key);
        _xmlWriter.WriteAttributeString("value", value);
        _xmlWriter.WriteAttributeStringOpt("cache-type", cacheType);
        _xmlWriter.WriteEndElement();
    }

    public void CacheRemoveValue(string key, string? cacheType)
    {
        _xmlWriter.WriteStartElement("cache-remove-value");
        _xmlWriter.WriteAttributeString("key", key);
        _xmlWriter.WriteAttributeStringOpt("cache-type", cacheType);
        _xmlWriter.WriteEndElement();
    }

    internal void CheckHeader(string name, string failedCheckHttpCode, string failedCheckErrorMessage,
        string ignoreCase, Action? writeValues)
    {
        _xmlWriter.WriteStartElement("check-header");
        _xmlWriter.WriteAttributeString("name", name);
        _xmlWriter.WriteAttributeString("failed-check-http-code", failedCheckHttpCode);
        _xmlWriter.WriteAttributeString("failed-check-error-message", failedCheckErrorMessage);
        _xmlWriter.WriteAttributeString("ignore-case", ignoreCase);
        if (writeValues is not null) writeValues();
        _xmlWriter.WriteEndElement();
    }
    public void CheckHeaderValue(string value)
    {
        _xmlWriter.WriteElementString("value", value);
    }

    internal void Choose(Action actions)
    {
        _xmlWriter.WriteStartElement("choose");
        actions();
        _xmlWriter.WriteEndElement();
    }

    internal void ChooseWhen(string condition, Action actions)
    {
        _xmlWriter.WriteStartElement("when");
        _xmlWriter.WriteAttributeString("condition", condition);
        actions();
        _xmlWriter.WriteEndElement();
    }

    internal void ChooseOtherwise(Action actions)
    {
        _xmlWriter.WriteStartElement("otherwise");
        actions();
        _xmlWriter.WriteEndElement();
    }

    public void Cors(Action writeValues, bool? allowCredentials, bool? terminateUnmatchedRequests)
    {
        _xmlWriter.WriteStartElement("cors");
        _xmlWriter.WriteAttributeStringOpt("allow-credentials", BoolValue(allowCredentials));
        _xmlWriter.WriteAttributeStringOpt("terminate-unmatched-request", BoolValue(terminateUnmatchedRequests));
        writeValues();
        _xmlWriter.WriteEndElement();
    }
    internal void CorsAllowedOrigins(Action origins)
    {
        _xmlWriter.WriteStartElement("allowed-origins");
        origins();
        _xmlWriter.WriteEndElement();
    }
    internal void CorsAllowedOrigin(string origin)
    {
        _xmlWriter.WriteElementString("origin", origin);
    }
    internal void CorsAllowedMethods(Action methods, string? preflightResultMaxAge)
    {
        _xmlWriter.WriteStartElement("allowed-methods");
        _xmlWriter.WriteAttributeStringOpt("pre-flight-max-age", preflightResultMaxAge);
        methods();
        _xmlWriter.WriteEndElement();
    }
    internal void CorsAllowedMethod(string method)
    {
        _xmlWriter.WriteElementString("method", method);
    }
    internal void CorsAllowedHeaders(Action headers)
    {
        _xmlWriter.WriteStartElement("allowed-headers");
        headers();
        _xmlWriter.WriteEndElement();
    }
    internal void CorsExposedHeaders(Action headers)
    {
        _xmlWriter.WriteStartElement("exposed-headers");
        headers();
        _xmlWriter.WriteEndElement();
    }
    internal void CorsHeader(string header)
    {
        _xmlWriter.WriteElementString("header", header);
    }

    public void SetBody(string body, bool liquidTemplate = false)
    {
        _xmlWriter.WriteStartElement("set-body");
        if (liquidTemplate)
            _xmlWriter.WriteAttributeString("template", "liquid");
        _xmlWriter.WriteString(body);
        _xmlWriter.WriteEndElement();
    }
}

internal static class XmlWriterExtensions
{
    public static void WriteAttributeStringOpt(this XmlWriter xmlWriter, string name, string? value)
    {
        if (!String.IsNullOrEmpty(value))
            xmlWriter.WriteAttributeString(name, value);
    }
}